### ISSUE TITLE
小米网关可以使用吗？

### ISSUE THREAD

**Issue by Tao173** [shaonianzhentan/xiaomi_radio#1]
如题，小米网关2代有收音机功能，这个可以兼容么？

**Comment by shaonianzhentan** [comment]
> 如题，小米网关2代有收音机功能，这个可以兼容么？

我没有这个设备，没法测试兼容性

**Comment by Tao173** [comment]
好的，谢谢，我试试看。

**Comment by Tao173** [comment]
> > 如题，小米网关2代有收音机功能，这个可以兼容么？
> 
> 我没有这个设备，没法测试兼容性

已测试，收音机可以。
