### ISSUE TITLE
这么实用的插件不考虑更新一下吗？

### ISSUE THREAD

**Issue by CCZU1623** [shaonianzhentan/xiaomi_radio#5]
新版本HA已经不能使用这个插件了

**Comment by shaonianzhentan** [comment]
我一直在用，没啥问题

请提供错误日志

**Comment by CCZU1623** [comment]
HA版本：2022.10.5,无法使用

Logger: homeassistant.components.media_player
Source: custom_components/xiaomi_radio/media_player.py:136
Integration: 播放器 ([documentation](https://www.home-assistant.io/integrations/media_player), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+media_player%22))
First occurred: 17:59:52 (1 occurrences)
Last logged: 17:59:52
xiaomi_radio: Error on device update!

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 493, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 703, in async_device_update
    await task
  File "/config/custom_components/xiaomi_radio/media_player.py", line 136, in async_update
    self._fm_list = result['chs']
KeyError: 'chs'

**Comment by shaonianzhentan** [comment]
该不是你的设备不支持吧，目前只测试了 米家空调伴侣（就是那款超级超级老的圆形的那款）

**Comment by CCZU1623** [comment]
我有3款设备，分别是米家空调伴侣1代（圆形的）、米家2代网关（带喇叭的那款白色的）、aqara空调伴侣升级版，都试过，并且都会出现这个问题。同时我也试过降级HA版本，您的插件最低支持到2021.3.0版本，发现并不是HA版本的问题，每个版本都会出现这种问题。现在考虑是不是米家空调伴侣的固件版本问题？我的米家空调伴侣1代固件版本：1.4.1_156.0148。aqara空调伴侣升级版固件：1.4.1_146.0149。二代网关固件版本：1.4.1_176.0220。您的空调伴侣1代固件版本跟我用的一样吗？

**Comment by shaonianzhentan** [comment]
我一般都会用新版的HA，极少会出现版本不兼容的情况

如果你的电台收藏列表为空，那就去米家空调伴侣里收藏几个然后再试试

不确定是不是因为没有读取到广播电台列表产生的异常

**Comment by CCZU1623** [comment]
感谢开发者！通过收藏电台的形式，现在已成功调用米家空调伴侣1代、米家网关、绿米空调伴侣升级版的喇叭。实测插件可以完美支持的型号有：米家1代空调伴侣 lumi-acpartner-v2，型号：KTBL02LM、米家多功能网关2代 lumi-gateway-v3 型号：DGNWG02LM、绿米空调伴侣升级版 lumi-acpartner-v3 型号：KTBL11LM。问题已解决，非插件原因，此问题已关闭。
