### ISSUE TITLE
2023.5.0报错无法使用，求助~

### ISSUE THREAD

**Issue by yuyuye84** [shaonianzhentan/xiaomi_radio#6]
报告大佬，
2023.5.0报错无法使用啦，求助~

Logger: homeassistant.config_entries
Source: custom_components/xiaomi_radio/__init__.py:10
Integration: 小米电台 ([documentation](https://github.com/shaonianzhentan/xiaomi_radio))
First occurred: 12:24:54 (1 occurrences)
Last logged: 12:24:54

Error setting up entry xiaomi_radio for xiaomi_radio
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/xiaomi_radio/__init__.py", line 10, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by shaonianzhentan** [comment]
已修复
